package com.nexa.pipe

import android.util.Log

object IrohProxy {
    private const val TAG = "IrohProxy"
    private var nativeLoaded = false

    /** Result codes returned by the native entry points. */
    const val RESULT_OK = 0
    const val RESULT_ERROR = -1

    /**
     * Configuration error: the request cannot succeed as configured, so retrying with another
     * port is pointless. Read [nativeTakeLastError] for the human-readable reason.
     */
    const val RESULT_CONFIG_ERROR = -2

    init {
        try {
            System.loadLibrary("nexapipe_client")
            nativeInit()
            nativeLoaded = true
            Log.d(TAG, "Native library loaded successfully")
        } catch (e: UnsatisfiedLinkError) {
            Log.e(TAG, "Failed to load native library: ${e.message}", e)
            nativeLoaded = false
        }
    }

    fun isNativeLoaded(): Boolean {
        return nativeLoaded
    }

    private external fun nativeInit(): Int

    /**
     * Injects the list of system DNS servers (comma-separated IPs, e.g.
     * "192.168.1.1,8.8.8.8"). Must be called before nativeStartIroh.
     *
     * By default iroh fails to read the system DNS on Android through JNI and
     * falls back to Google DNS, which is unreliable behind restrictive
     * networks. Kotlin reads the system DNS from ConnectivityManager and
     * injects it here; nativeStartIroh then builds a DnsResolver from it,
     * bypassing iroh's broken JNI path.
     */
    external fun nativeSetDnsServers(dnsServers: String): Int

    /**
     * Injects pre-resolved IPs for iroh infrastructure domains, in the form
     * "domain=ip1,ip2;domain2=ip3,ip4". Must be called before nativeStartIroh.
     *
     * The Great Firewall (GFW) drops UDP DNS responses for iroh.link domains,
     * so iroh's internal hickory resolver times out on dns.iroh.link and
     * *.relay.n0.iroh.link. Kotlin pre-resolves those domains with the system
     * DNS (InetAddress, which may go through DoT / Private DNS and bypass the
     * GFW) and injects the result here; nativeStartIroh builds an
     * OverrideResolver that returns the pre-resolved IPs directly for these
     * domains.
     */
    external fun nativeSetDnsOverride(overrides: String): Int

    /**
     * Configures the relay mode, the custom relay URL and the relay's auth token.
     * relayMode:  "pinned" (one fixed N0 relay, the default), "default" (all N0
     *             relays), "disabled" (no relay transport at all), "custom".
     * relayUrl:   only used when relayMode="custom"; must be a full relay URL.
     *             Setting it without a relayMode means "custom" too.
     * authToken:  bearer token for a custom relay that requires one. Only used
     *             together with relayUrl.
     * Must be called before nativeStartIroh.
     */
    external fun nativeSetRelayConfig(relayMode: String, relayUrl: String, authToken: String): Int

    /**
     * Configures the 2FA credentials of one endpoint.
     * nodeId:    endpoint ID the credentials belong to.
     * clientId:  must match the ID configured in that server's [auth.clients].
     * secret:    Base32-encoded TOTP key (generated by `nexapipe --generate-2fa`).
     * algorithm: "sha1" / "sha256" / "sha512".
     * Must be called before nativeStartProxy / nativeStartProxyLegacy.
     *
     * Only this endpoint's connections authenticate with these credentials;
     * endpoints without any keep none, so servers that do not share a secret
     * stay reachable. Call [nativeClearNodeTwoFactor] first when re-reading the
     * configuration, otherwise an endpoint whose 2FA was switched off keeps the
     * credentials of an earlier connect.
     */
    external fun nativeSetTwoFactorForNode(
        nodeId: String,
        clientId: String,
        secret: String,
        algorithm: String
    ): Int

    /**
     * Drops every credential set with [nativeSetTwoFactorForNode].
     *
     * Read the configuration back through this pair on every connect: the
     * native table outlives a single session, so stale entries would otherwise
     * keep authenticating endpoints that no longer have 2FA.
     */
    external fun nativeClearNodeTwoFactor(): Int

    /**
     * Configures 2FA credentials for *every* endpoint at once.
     *
     * Kept for callers that really do share one secret across all servers;
     * per-endpoint credentials registered with [nativeSetTwoFactorForNode]
     * override it. Must be called before nativeStartProxy /
     * nativeStartProxyLegacy.
     */
    external fun nativeSetTwoFactor(clientId: String, secret: String, algorithm: String): Int

    external fun nativeStartIroh(): String?

    external fun nativeStartProxy(listenPort: Int): Int

    /**
     * Human-readable reason behind the last failed native call, cleared on read.
     * Null when there is nothing to report.
     *
     * The start entry points return only an int, so without this the caller cannot tell a bad
     * node ID from an occupied port.
     */
    external fun nativeTakeLastError(): String?

    /**
     * Validates a node ID with the same parser the connection path uses.
     *
     * @return null when the ID is valid, otherwise the parser's reason.
     */
    external fun nativeValidateNodeId(nodeId: String): String?

    /**
     * Pre-connect (warm-up): establish one iroh connection per configured
     * backend and cache it in the shared connection pool, so the first real
     * request after the VPN is up does not wait for the QUIC/relay handshake.
     * The TUN proxy and the local proxy share the same EndpointGroup / pool.
     * Must be called after nativeStartProxy and before the VPN is established.
     * @return number of backends warmed, or -1 on failure.
     */
    external fun nativePreconnect(): Int

    /**
     * How each configured backend is currently reached: one `<endpointId>=<kind>` pair per
     * backend, joined with `;`, where `kind` is `direct`, `relay` or `unknown`.
     *
     * This is the runtime answer, read off the path iroh actually selected — not the
     * configured relay URL, which only names a relay that may be used. A backend that has
     * never connected reports `unknown`.
     *
     * Must be called after nativeStartProxy (which creates the EndpointGroup).
     * @return the encoded list, or null when nothing has been started yet.
     */
    external fun nativeLinkKinds(): String?

    /**
     * Closes and forgets every cached backend connection, keeping the iroh endpoint.
     *
     * The recovery step for a network switch (Wi-Fi <-> cellular, or a network that came
     * back). A tunnel can be rebuilt on the new network and still be unusable: the
     * connections inside it were opened on the old one, and QUIC does not notice — a
     * connection whose path is dead still reports no close reason, so the pool keeps handing
     * it out and every proxied request fails. This drops them, so the next request dials on
     * the network that is actually up. Follow it with [nativePreconnect] to warm the pool
     * again.
     *
     * Must be called after nativeStartProxy (which creates the EndpointGroup).
     * @return 0 when the connections were dropped, -1 when nothing has been started yet.
     */
    external fun nativeDropConnections(): Int

    external fun nativeStartProxyLegacy(listenPort: Int, targetEndpointId: String): Int

    external fun nativeStopProxy(): Int

    external fun nativeAddNode(nodeId: String, domains: String): Int

    external fun nativeAddDomainMapping(domain: String, nodeId: String): Int

    external fun nativeRemoveNode(nodeId: String): Int

    external fun nativeClearNodes(): Int

    external fun nativeAddDomain(domain: String): Int

    external fun nativeRemoveDomain(domain: String): Int

    external fun nativeDestroy(): Int

    /**
     * Starts the TUN proxy: smoltcp handles the TCP/UDP traffic of the TUN fd
     * on the Rust side.
     *
     * Must be called after nativeStartProxy (the endpoint_group exists) and
     * after the VPN has been established. Kotlin transfers fd ownership to Rust
     * through ParcelFileDescriptor.detachFd(); Rust duplicates it (read/write)
     * and then closes the original fd.
     *
     * @param tunFd raw fd returned by ParcelFileDescriptor.detachFd()
     * @param proxyDomains comma-separated list of proxied domains
     * @return 0 on success, -1 on failure
     */
    external fun nativeStartTunProxy(
        tunFd: Int,
        proxyDomains: String
    ): Int

    /**
     * Stops the TUN proxy: aborts all background tasks and closes the
     * duplicated fds. Called by NexaVpnService.stopVPN() before the TUN fd is
     * closed.
     */
    external fun nativeStopTunProxy(): Int
}
